include::./_attribute.adoc[]
= Asciidocテンプレート

== はじめに
AsciiDoc、Draw.io、PlantUMLを使ってソフトウェア仕様書を作るためのテンプレートです。

== AsciiDocとは
AsciiDocは、プレーンテキストで記述できる強力なマークアップ言語であり、技術文書やマニュアルなど、複雑な構造を持つドキュメントの作成に適しています。 +
Markdownと比較すると、より高度な文書構造を記述できる点が特徴です。 +
また、HTML、PDF、EPUBなど、多様な出力形式に対応しているため、作成したドキュメントをさまざまな媒体で公開できます。 +
AsciiDocの仕様は明確に定義されているため、一貫性のある文書作成を支援します。 +
そのため、複数人で共同作業を行う場合や、長期にわたってメンテナンスが必要なドキュメントを作成する場合にも適しています。 +
ただし、Markdownと比較すると記法が複雑であるため、習得にはやや時間がかかります。 +
しかし、その分、高度な表現力と柔軟性を備えており、複雑なドキュメント作成のニーズに応えることができます。

AsciiDocは、文書を記述するための軽量マークアップ言語です。 +
Markdownと比較して、より多くの機能を持ち、とくにドキュメントの構造化やスタイルのカスタマイズが容易です。 +
AsciiDocは、技術文書や書籍、Webコンテンツなど、さまざまな形式のドキュメントを作成するために使用されます。

Markdownを書いたことがあれば似たような感じで書けます。 +
困ったら以下を参考にどう書くのか調べながら書いてください。

link:https://takumon.github.io/asciidoc-syntax-quick-reference-japanese-translation/[Asciidoctor文法クイックリファレンス（日本語訳）]

== Markdownとの違い
違いは以下にまとめられています。

link:https://asciidoctor.org/docs/asciidoc-vs-markdown/[Compare AsciiDoc to Markdown]

よく使用し、Markdownと書き方が違うものを示す。

=== 見出し
Markdownでは``\#``で記述するがasciidocでは``=``を使用する。 +
Markdownの``#``と同様に``=``の数でレベルを表現する。

----
= 見出し1
== 見出し2
=== 見出し3
----

=== 箇条書き
Markdownでは``-``で記述するがasciidocでは``\*``を使用する。 +
箇条書きのインデントはMarkdownでは字下げして``-``であったが、asciidocでは``*``の数で表現する。

----
* 箇条書き1
* 箇条書き2
** 1段下げ
*** 2段下げ
----

* 箇条書き1
* 箇条書き2
** 1段下げ
*** 2段下げ

=== 番号付きの箇条書き
Markdownでは``{数値}.``で記述するがasciidocでは``.``を使用する。 +
``*``と同様に``.``の数で字下げする。

----
. 番号付き1
.. 1段下げ
... 2段下げ
----

. 番号付き1
.. 1段下げ
... 2段下げ

=== テーブル
テーブルは|===で始めて|===で終わるブロック内に書きます。
行の終わりの|は不要です。
ヘッダーはヘッダーとデータの行の間に空白を入れるか、ブロックの頭にオプションでヘッダーを指定します。
オプションの指定で幅の自動調整も一緒にできるのでブロックの頭にオプション指定したほうが良いでしょう。

----
[options="header,autowidth"]
|===
|col1|col2|col3
|data1|data2|data3
|===
----

[options="header,autowidth"]
|===
|col1|col2|col3
|data1|data2|data3
|===

セルの結合もできます。

----
[options="header,autowidth"]
|====
|col1|col2|col3

|1-1
2+|整数+で横結合
|2-1
.2+|.整数+で縦結合
|2-3
|3-1
|3-3
|4-1
2.2+|整数.整数+で縦横結合
|5-1
|====
----

[options="header,autowidth"]
|====
|col1|col2|col3

|1-1
2+|整数+で横結合
|2-1
.2+|.整数+で縦結合
|2-3
|3-1
|3-3
|4-1
2.2+|整数.整数+で縦横結合
|5-1
|====

=== PlantUML
asciidoc-diagramを使用すると、PlantUMLを直接記述できます。 +
（画像を自動生成して挿入してくれる）

別ファイルにしてincludeもできます。

[plantuml, target="plantuml-example"]
----
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
----
